---
sudo: required
services: docker
language: python
dist: xenial

python:
  - "3.6"

branches:
  only:
  - master
  - travis

before_script:
  - sudo apt-get update
  - sudo apt-get install google-chrome-stable=73.0.3683.86-1 -y
  - wget https://chromedriver.storage.googleapis.com/73.0.3683.68/chromedriver_linux64.zip
  - unzip chromedriver_linux64.zip -d /home/travis/bin

install:
  - pip install selenium

jobs:
  include:
    - stage: tests
      script:
      - make travis-runtests
